### PR TITLE
Add `latest` tag for inputs.version

### PR DESCRIPTION
**Pull request by mintyfrankie**
Hi @yusancky, thanks for putting this useful action in place!

I'd suggest adding a `latest` tag for `inputs.version`, so that developers don't have to manually update the version number every time when Typst publishes a new release.

### CODE REVIEW

**Comment by yusancky** [comment]
In my commit, I used the `? :` expression in the context, but it is no longer supported. I'm so sorry, can you please use `git reset` and force push to roll back to 072e35f?

**Comment by mintyfrankie** [comment]
Yeah I looked at the lastest Github Action documentation and found that the `if` context seems to be the only way to use conditionals. 

I've patched a new commit to revert your `f23c42d` commit. Do tell me if there are other things to test out or modify!

**Comment by yusancky** [comment]
Thank you for your contribution, it's simply great!

**Comment by mintyfrankie** [comment]
Perfect thanks @yusancky !

**Pull request merged**
